services:
  postgres:
    image: yeuda4222/intelligent-investor-db:latest
    container_name: intelligent_investor_hub_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intelligent_investor_prod_db
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d intelligent_investor_prod_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: yeuda4222/intelligent-investor-backend:latest
    container_name: intelligent_investor_hub_backend
    restart: always
    environment:
      PORT: 5050
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/intelligent_investor_prod_db?schema=public
    ports:
      - "5052:5050"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "node src/server.js"

  frontend:
    image: yeuda4222/intelligent-investor-frontend:latest
    container_name: intelligent_investor_hub_frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend
